apiVersion: v1
kind: Service
metadata:
  name: moviemood-service
spec:
  selector:
    app: moviemood
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30000