apiVersion: v1
kind: Service
metadata:
  name: moviemood-service
spec:
  selector:
    app: moviemood
  type: LoadBalancer  # NodePort
  ports:
    - protocol: TCP 
      port: 5173
      targetPort: 5173 # the port of frontend
      nodePort: 30000 # the port of node